name: Test Auto-Tag (manual)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  test-create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: pivvenit/workflow-actions
          ref: v3
          token: ${{ secrets.WORKFLOW_COMPOSITE_ACTIONS_PAT }}
          path: .github/workflow-actions
      - uses: ./.github/workflow-actions/auto-tag
